name: i_trolley
description: Companion App for i - Trolley

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  mobile_scanner: ^1.1.1
  flutter_blue_plus: ^1.1.3
  flutter_reactive_ble: ^5.0.2

  firebase_core: ^1.17.0
  cloud_firestore: ^3.1.16


  flutter_vibrate: ^1.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true


  assets:
    - assets/playstore.png
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Light.ttf

    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/SourceSansPro-ExtraLight.ttf